config/routes.rb
Rails.application.routes.draw do

  resources :estimates do
    resource :download, only: [:show]
  end 
  root 'estimates#index' 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estimate.rb
class Estimate < ApplicationRecord

end

app/models/invoice_pdf.rb
require "render_anywhere"
class InvoicePdf < ApplicationRecord
	include RenderAnywhere
 
  def initialize(estimate)
    @estimate = estimate
  end
 
  def to_pdf
    kit = PDFKit.new(as_html, page_size: 'A4')
    kit.to_file("#{Rails.root}/public/invoice.pdf")
  end
 
  def filename
    "Estimate #{estimate.id}.pdf"
  end
 
  private
 
    attr_reader :estimate
 
    def as_html
      render template: "estimates/pdf", layout: "estimate_pdf", locals: { estimate: estimate }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
 
  def show
    respond_to do |format|
      format.pdf { send_invoice_pdf }
 
      if Rails.env.development?
        format.html { render_sample_html }
      end
    end
  end
 
  private
 
  def estimate
    Estimate.find(params[:estimate_id])
  end
 
  def estimate_pdf
    InvoicePdf.new(estimate)
  end
 
  def send_invoice_pdf
    send_file estimate_pdf.to_pdf,
      filename: estimate_pdf.filename,
      type: "application/pdf",
      disposition: "inline"
  end
 
  def render_sample_html
    render template: "estimates/pdf", layout: "estimate_pdf", locals: { estimate: estimate }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/edit.html.erb
<h1>Editing Estimate</h1>

<%= render 'form', estimate: @estimate %>

<%= link_to 'Show', @estimate %> |
<%= link_to 'Back', estimates_path %>

app/views/estimates/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estimates.each do |estimate| %>
      <tr>
        <td><%= link_to 'Show', estimate %></td>
        <td><%= link_to 'Edit', edit_estimate_path(estimate) %></td>
        <td><%= link_to 'Destroy', estimate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estimate', new_estimate_path %>

app/views/estimates/new.html.erb
<h1>New Estimate</h1>

<%= render 'form', estimate: @estimate %>

<%= link_to 'Back', estimates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield %>
  </body>
</html>

app/views/layouts/estimate_pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title>Envato Invoices</title>
  <style>
    <%= Rails.application.assets.find_asset('application.scss').to_s %>
  </style>
</head>
<body>
	<div style="text-align: center; margin-top: 0px;">
<h6>Estimate/Order For Service</h6>
<h6>Rainbow Moving & Storage</h6>
<h6>12105 Action Lane, Unit 1B</h6>
<h6>Walorf, MD 20601</h6>
<h6>(301)843-3541 1800-942-8548</h6>
	</div>

  <%= yield %>
</body>
</html>